name: Deploy para GitHub Pages

on:
  push:
    branches: [ "main" ] # Executa automaticamente quando algo é enviado para main
  workflow_run:
    workflows: ["ci"]   # nome exato do outro workflow
    types: 
      - completed


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5  # Prepara configurações internas do Pages (tokens, ambiente etc.)

      - name: Fazer upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          name: my-pages-artifact   # Nome customizado do artefato

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4  # Publica no GitHub Pages
        with:
          artifact_name: my-pages-artifact 